### ISSUE TITLE
Release proposal: 15.0.0

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard#171]
We'll have to do a major version to get ESLint 7.x support, and I wanted to see if there is anything else we want to merge in as well. My preliminary list:

- [ ] ESLint 7 #169 #170 
- [ ] Object Shorthand #166 
- [ ] Cleanup #160 
- [ ] ES2020 globals #156 
- [ ] Remove no-inner-declarations #154

Need to check up to date eco system breakage: 
- [ ] no-var #152 
- [ ] catch-or-return #148
- [ ] multiline-comment-style #94

**Comment by LinusU** [comment]
I have revised my list and want to do a bit less controversial release.

#166 &  #152 breaks compatibility with older browsers, and it seems like not everyone is ready for that just yet.

#148 seems like it could bring with a number of false positives, which generally have been something that we really want to avoid, so that Standard "gets out of your way" as it were.

#94 has some eco system breakage that we should investigate and potentially tweak the rule before merging it, or dropping the rule...

With that said I want to cut a 15 release that mainly focuses on the upgrade to ESLint 7, and adding compatibility with modern code that uses ES2020 features.

Unless no-one objects in a few days, I shall cut a release with just the PRs in the first group 🎉

**Comment by mightyiam** [comment]
How about https://github.com/standard/standard/issues/1431?

**Comment by Raynos** [comment]
Rolling out eslint 7 as a single upgrade is a good idea.

I’d be happy to help with that.

**Comment by sheerun** [comment]
Could you also enable `offsetTernaryExpressions` indent rule? It should fix https://github.com/standard/standard/issues/927

**Comment by voxpelli** [comment]
Would you like any help in pushing this forward @LinusU / @feross?

Getting a release out that targets ESLint 7 is becoming ever more useful and if you want to I can give you a hand in pushing things forward.

**Comment by feross** [comment]
I'm working on this today.

**Comment by ankurnarkhede** [comment]
How about #174 ? Can you check if it can be done?

**Comment by feross** [comment]
I'm going to save the rules which have huge amounts of breaking changes for a future version.
