### ISSUE TITLE
Ship final version of `17.0.0`

### ISSUE THREAD

**Issue by voxpelli** [standard/eslint-config-standard#208]
Me and @Divlo shipped `17.0.0-0` today, #203, following the merge of #193.

`17.0.0-0` is a _prerelease_.

One can install it using `eslint-config-standard@next`

Being a pre-release, `17.0.0-0` comes with no guarantees in regards to support / breaking changes etc. It exists to facilitate early feedback, from the wider community as well from our selves.

Next steps before we will ship a stable release of `17.0.0` are:

* [x] Merge new `standard-engine` into `standard`: https://github.com/standard/standard/pull/1754
* [x] Ship a new major of `eslint-config-standard-jsx`
* [x] Update `standard` to `17.0.0-0` of this module + the new major of `eslint-config-standard-jsx`
* [x] Ship a `17.0.0-0` of `standard` to start getting some feedback on ecosystem compatibility
* [x] When we're confident that the ecosystem is ready for a stable `17.0.0`, roll one for this module...
  * [x] Ship a `17.x` compliant update to [`vscode-standard`](https://github.com/standard/vscode-standard) (https://github.com/standard/vscode-standard/issues/375)
  * [x] All of the [external tests](https://github.com/standard/standard/actions) in `standard` passes (https://github.com/standard/standard/issues/1777)
  * [x] `standard-engine` generated types (https://github.com/standard/standard-engine/issues/279) + CI succeeds
* [x] ...and then a stable `11.0.0` of `eslint-config-standard-jsx`
* [x] ~~...and then a stable `12.0.0` of `eslint-config-standard-react`~~ **Not used, skipped**
* [x] ...and then a stable `15.0.0` of `standard-engine`
* [ ] ...and then a stable `17.0.0` of `standard`...
* [ ] ...and then new version of the long tail of `standard`-siblings, like `semistandard`...
* [ ] ...then close this issue and the `17.0.0` milestone

In the meanwhile, please report any breakage you discover 🙏

**Comment by voxpelli** [comment]
Prerelease `17.0.0-0` of `standard` is now released: https://github.com/standard/standard/releases/tag/v17.0.0-0

We will be checking the stability of this ourselves, but would love for as many of our users to test it out as well and report back to us whether it's time to party or time to head back into the workshop and reshape things. Thanks 🙏

**Comment by JanFellner** [comment]
Any update on the final 17? Working with it since 3 weeks, looking good to me...

**Comment by pgnd** [comment]
@feross 
understand that there are many moving parts here before full release

could 'latest' tag, at least, be bumped to pick up dep change @ 

https://github.com/standard/eslint-config-standard/pull/215

? it's currently causing breakage, e.g. in VSCode's Redhat Dependency Analytics / snyk usage.

**Comment by voxpelli** [comment]
@pgnd What breakage is caused where?

The `latest` tag will and should always be pointing to the newest stable release.

@Divlo We can release a stable before @feross chimes in, since its just a dependency update. We still have https://github.com/standard/standard/issues/1777 to fix though

**Comment by pgnd** [comment]
@voxpelli understood.  if i can get RH tool working in my env, I'll readd it and get the details to you.  Atm, it's a 'doorstop'.

```
yarn add --dev eslint-config-standard@next
```
installs 17.0.0-1, from Jan 31 tag

which does NOT yet contain the relevant fix from
```
https://github.com/standard/eslint-config-standard/pull/215
```

**Comment by pgnd** [comment]
https://github.com/standard/eslint-config-standard/pull/215#issuecomment-1049704876
-->
https://github.com/standard/eslint-config-standard/issues/216

**Comment by christophernruud** [comment]
a pre-release 17.0.0-2 tag could allow building transient dependencies that rely on eslint-config-n@latest without getting npm errors, that's all. We build an in-house eslint library for vue-cli5, and as of right now we have a breakage because of conflicting versions ubtil 17.0.0 i s released or a new beta tag is posted. If possible, we'd like to not do yet another fork of an eslint-related project 😅

**Comment by voxpelli** [comment]
I can try to roll one later, but if there’s no _need_ for you to run with a newer version of `eslint-plugin-n` then you can simply downgrade it to the version that `standard` expects.

**Comment by JanFellner** [comment]
Ping :) I always need to manually handle the result of npm outdated for this repo. Any chance to get that done?
![grafik](https://user-images.githubusercontent.com/53753460/158804496-82f3054c-43c5-4f4d-bb4f-c4c4364d66bf.png)

**Comment by voxpelli** [comment]
@JanFellner Feel free to help going through https://github.com/standard/standard/issues/1777 :) That's the main blocker.

We won't release this as stable without having passing integration tests for the wider community as failures there can just as much mean that we had unintended rule changes in the ESLint 8 move as it can mean that the external projects have gone bad themselves.

Also: If you know of large projects using this that aren't present in the external tests there, then please make an issue or PR there to suggest adding them. The more insight we can get into community breakage / support, the more confident we can become in shipping things quickly.

(Right now I myself am pretty busy with my paid job, so haven't had time to look at the mentioned issues in a while)

**Comment by pgnd** [comment]
> Feel free to help going through standard/standard#1777

looking, the aparently still open issues are
```
                                              LAST COMMIT
                                             _____________
https://github.com/feross/simple-get          2022-03-17
https://github.com/webtorrent/webtorrent      2022-03-30
https://github.com/marcbachmann/node-html-pdf 2021-05-07
https://github.com/feross/chrome-net          2020-10-29
https://github.com/libp2p/js-libp2p-tcp       2022-03-16
https://github.com/feross/safe-buffer         2020-10-29
https://github.com/yargs/yargs-parser         2022-02-27
https://github.com/maxogden/extract-zip       2021-08-01
```

Some are recently active, some, clearly ... aren't.

iiuc, no eslint8-ready `eslint-config-standard` v17x final release until each/all of those are updated?

**Comment by Divlo** [comment]
@pgnd 

> iiuc, no eslint8-ready eslint-config-standard v17x final release until each/all of those are updated? or replaced?

I don't think strictly that we should fix all the `test-external` before releasing v17, even if it would be better for sure, I don't think this is necessary as most of the failing ones are unmaintained repo with no activity recently, and also most of the repo in `test-external` still use `var` keyword to declare variables (they are mostly old codebases)...

I think it would be worth disabling some of them (see this file: https://github.com/standard/standard/blob/master/test/external/test.json).
Also, we might consider doing a major "refactoring" for this, and only do `test-external` for a repo that at least use v16 of `standard` and that is actively maintained (I know actively might be subjective but I think we should define what is "active" and we can pretty much agree that repo with no commits since 3 years is unmaintained), I saw some of them still using `standard` v14.

**Comment by Tofandel** [comment]
I agree, this also seems to be the backwards way of doing this, it's after all a major upgrade, so maybe there should be a PR for those projects to ease their upgrade, but if that PR is discarded or the project is not even using an up to date version of standard or their is no activity on the project they should definitely not block the upgrade in itself. I know some projects will be reluctant to change from var to const because they want to keep backward compatibility with the super old nodejs versions, and well we can't blame them for not wanting to release a major over code style

Adoption won't happen until it is fully released, and those forgotten projects will either update in their own time or get forked into oblivion

**Comment by JanFellner** [comment]
@voxpelli whats your thinking about removing outdated packages as mentioned by @Divlo and @Tofandel.
This currently seems to block the final shipment of v17?

**Comment by voxpelli** [comment]
> whats your thinking about removing outdated packages as mentioned by @Divlo and @Tofandel.
> This currently seems to block the final shipment of v17?

I'm 👍 on that, though I want to go through them to see if the failures are because of an unintended change or because of eg. lack of maintenance on their path.

I'll try to find time soon to look at what eg. @Tofandel summarised here. Main blocker from my side has been my time 🙈
